version: '3.7'
services:
  go_app:
    container_name: go-app
    image: inkz/gobooking
    build: 
      context: .
      dockerfile: dockerfile
    environment:
      DB_SOURCE: "postgres://postgres:postgres@go_db:5432/simple_bank?sslmode=disable"
      SERVER_ADDRESS: "0.0.0.0:8000"
      TOKEN_SYMMETRIC_KEY: "12345678901234567890123456789012"
      ACCESS_TOKEN_DURATION: "15m"
      DB_DRIVER: "postgres"
      REDIS_ADDRESS: "redis:6379"
    ports:
      - "8000:8000"
    depends_on:
      - go_db
    entrypoint: ["/app/wait-for.sh","go_db:5432", "--", "/app/start.sh"]
    command: [ "/app/main" ]

  go_db:
    container_name: go_db
    image: postgres:12
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: simple_bank
    ports:
      - "5000:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

volumes:  
  pgdata: {}
